"use client";
import { formatBulanSingkat } from "@/lib/eprom-api";
type Titik={bulan:string;planned:number;actual:number;deviasi:number}; type Seri={id:number;namaProject:string;data:Titik[]};
const W=720,H=320,L=42,R=64,T=24,B=48,ORANYE="#ef7100",BIRU="#0868f6",WARNA=["#0868f6","#07984c","#ef7100","#7a4ce0","#d53535","#0aa3a3"];
export function ProgressTrendChart({seri,detail=false}:{seri:Seri[];detail?:boolean}){const tanggal=Array.from(new Set(seri.flatMap(s=>s.data.map(d=>d.bulan)))).sort();if(!tanggal.length)return null;const nilai=seri.flatMap(s=>s.data.flatMap(d=>detail?[d.planned,d.actual]:[d.actual]));const maxNilai=Math.max(...nilai,1),maxY=maxNilai<=25?25:Math.min(100,Math.ceil(maxNilai*1.2/5)*5),width=Math.max(W,tanggal.length*110),aw=width-L-R,ah=H-T-B,x=(v:string)=>tanggal.length===1?L+aw/2:L+tanggal.indexOf(v)/(tanggal.length-1)*aw,y=(v:number)=>T+ah-Math.min(maxY,Math.max(0,v))/maxY*ah,ticks=Array.from({length:5},(_,i)=>Math.round(maxY*i/4)),path=(d:Titik[],k:"planned"|"actual")=>d.map(a=>`${x(a.bulan)},${y(a[k])}`).join(" ");return <div style={{width:"100%",overflowX:"auto"}}><svg viewBox={`0 0 ${width} ${H}`} style={{width,height:H,minWidth:420,display:"block"}}>{ticks.map(p=><g key={p}><line x1={L} x2={width-R} y1={y(p)} y2={y(p)} stroke="#dbe6f2" strokeDasharray={p?"5 7":undefined}/><text x={L-9} y={y(p)+4} textAnchor="end" fontSize={10} fill="#71839a">{p}%</text></g>)}{tanggal.map(t=><text key={t} x={x(t)} y={H-14} textAnchor="middle" fontSize={10} fill="#71839a">{formatBulanSingkat(t)}</text>)}{seri.map((s,si)=><g key={s.id}>{detail?<><polyline points={path(s.data,"planned")} fill="none" stroke={ORANYE} strokeWidth={3} strokeLinecap="round"/><polyline points={path(s.data,"actual")} fill="none" stroke={BIRU} strokeWidth={3} strokeLinecap="round"/>{s.data.map(d=>{const xp=x(d.bulan),yp=y(d.planned),ya=y(d.actual),positive=d.deviasi>=0,dev=`${positive?"+":""}${d.deviasi}%`;return <g key={d.bulan}><circle cx={xp} cy={yp} r={4} fill={ORANYE} stroke="white" strokeWidth={2}/><circle cx={xp} cy={ya} r={4} fill={BIRU} stroke="white" strokeWidth={2}/><text x={xp-8} y={yp-9} textAnchor="end" fontSize={10} fontWeight={800} fill={ORANYE}>P {d.planned}%</text><text x={xp+8} y={ya+15} textAnchor="start" fontSize={10} fontWeight={800} fill={BIRU}>A {d.actual}%</text><text x={xp} y={positive?Math.min(yp,ya)-25:Math.max(yp,ya)+29} textAnchor="middle" fontSize={10} fontWeight={800} fill={positive?"#078b49":"#d53535"}>{dev}</text></g>})}</>:<><polyline points={path(s.data,"actual")} fill="none" stroke={WARNA[si%WARNA.length]} strokeWidth={3} strokeLinecap="round"/>{s.data.map(d=><circle key={d.bulan} cx={x(d.bulan)} cy={y(d.actual)} r={4} fill={WARNA[si%WARNA.length]} stroke="white" strokeWidth={2}/>)}{s.data.at(-1)&&<text x={x(s.data.at(-1)!.bulan)+8} y={y(s.data.at(-1)!.actual)+4} fontSize={12} fontWeight={800} fill={WARNA[si%WARNA.length]}>{s.data.at(-1)!.actual}%</text>}</>}</g>)}</svg><div style={{display:"flex",flexWrap:"wrap",gap:16,marginTop:8,fontSize:12,color:"#34506f"}}>{detail&&<><span>?? Planned</span><span>?? Actual</span></>}{seri.map((s,i)=><span key={s.id}><i style={{display:"inline-block",width:10,height:10,borderRadius:99,background:detail?(i?BIRU:ORANYE):WARNA[i%WARNA.length],marginRight:6}}/>{s.namaProject}</span>)}</div></div>}




