"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, Fuel, Gauge, Truck } from "lucide-react";
import styles from "./transport.module.css";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:3001/api";
const token = () =>
  localStorage.getItem("hcga_access_token") ||
  sessionStorage.getItem("hcga_access_token") ||
  localStorage.getItem("access_token") ||
  sessionStorage.getItem("access_token") ||
  "";
type Point={name:string;value:number};
type Data={month:number;year:number;totals:{units:number;hm:number;liters:number;availability:number};availabilityByDepartment:Point[];hmByDepartment:Point[];hmPerShiftByUnit:Point[];litersByUnit:Point[]};
function Bars({data,suffix=""}:{data:Point[];suffix?:string}){const max=Math.max(1,...data.map(x=>x.value));return <div className={styles.bars}>{data.length?data.map(x=><div className={styles.barRow} key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.max(3,x.value/max*100)}%`}}/></div><strong>{x.value.toLocaleString("id-ID",{maximumFractionDigits:2})}{suffix}</strong></div>):<p className={styles.empty}>Belum ada data periode ini.</p>}</div>}
export default function TransportDashboard(){const now=new Date();const [month,setMonth]=useState(0);const [year,setYear]=useState(now.getFullYear());const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{let active=true;const load=async()=>{setLoading(true);setError("");try{const accessToken=token();if(!accessToken){throw new Error("Sesi login tidak ditemukan. Silakan login ulang.")}const response=await fetch(`${API}/transport/dashboard?month=${month}&year=${year}`,{headers:{Authorization:`Bearer ${accessToken}`}});const body=await response.json().catch(()=>null);if(!response.ok){throw new Error(Array.isArray(body?.message)?body.message.join(", "):body?.message||"Dashboard transportasi gagal dimuat")}if(active){setData(body)}}catch(err){if(active){setData(null);setError(err instanceof Error?err.message:"Dashboard transportasi gagal dimuat")}}finally{if(active)setLoading(false)}};void load();return()=>{active=false}},[month,year]);const years=useMemo(()=>Array.from({length:5},(_,i)=>now.getFullYear()-2+i),[]);return <section>
<div className={styles.hero}><div><span className={styles.heroIcon}><Truck/></span><div><h1>Dashboard Transportasi</h1><p>Ringkasan performance availability, kilometer/HM, dan pemakaian fuel.</p></div></div><div className={styles.filters}><select value={month} onChange={e=>setMonth(+e.target.value)}><option value={0}>Semua Bulan</option>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{new Date(2026,i).toLocaleString("id-ID",{month:"long"})}</option>)}</select><select value={year} onChange={e=>setYear(+e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></div></div>
{error?<div className={styles.pageError}>{error}</div>:loading||!data?<div className={styles.panel}>Memuat dashboard...</div>:<><div className={styles.cards}><article><Truck/><span>Total Unit</span><strong>{data.totals.units}</strong><small>No lambung aktif</small></article><article><Gauge/><span>Total HM</span><strong>{data.totals.hm.toLocaleString("id-ID",{maximumFractionDigits:2})}</strong><small>Kilometer/HM periode</small></article><article><Fuel/><span>Total Liter</span><strong>{data.totals.liters.toLocaleString("id-ID",{maximumFractionDigits:2})}</strong><small>Pemakaian fuel</small></article><article><Activity/><span>Availability</span><strong>{data.totals.availability.toFixed(2)}%</strong><small>Rata-rata UA</small></article></div>
<div className={styles.grid}><article className={styles.panel}><h3>Performance Availability LV/BUS</h3><div className={styles.availability}>{data.totals.availability.toFixed(2)}%</div></article><article className={styles.panel}><h3>Availability per Departemen</h3><Bars data={data.availabilityByDepartment} suffix="%"/></article><article className={styles.panel}><h3>Total HM per Departemen</h3><Bars data={data.hmByDepartment}/></article><article className={styles.panel}><h3>HM Pershift per Unit</h3><Bars data={data.hmPerShiftByUnit}/></article><article className={`${styles.panel} ${styles.full}`}><h3>Total Liter per No Lambung</h3><Bars data={data.litersByUnit}/></article></div></>}</section>}
