'use client';
import { Trash2, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import { tps3rApi, urlFotoTps3r, type FotoPenyerahanTps3r } from '@/lib/tps3r-api';
import styles from '../../project/tender/tender.module.css';
export default function Page(){
 const [data,setData]=useState<FotoPenyerahanTps3r[]>([]),[tanggal,setTanggal]=useState(new Date().toISOString().slice(0,10)),[foto,setFoto]=useState<File|null>(null),[error,setError]=useState('');
 const load=()=>tps3rApi.daftarFoto().then(setData).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
 const upload=async()=>{if(!foto)return setError('Pilih foto terlebih dahulu');try{await tps3rApi.tambahFoto(tanggal,foto);setFoto(null);load()}catch(e){setError(e instanceof Error?e.message:'Gagal upload')}};
 return <div className={styles.page}><div className={styles.headerRow}><div><h1>Foto Penyerahan Sampah</h1><p>Foto dokumentasi beserta tanggal penyerahan.</p></div></div>{error&&<p className={styles.errorText}>{error}</p>}<div className={styles.formCard} style={{display:'flex',gap:12,alignItems:'end',flexWrap:'wrap'}}><label>Tanggal<input type="date" value={tanggal} onChange={e=>setTanggal(e.target.value)}/></label><label>Foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFoto(e.target.files?.[0]??null)}/></label><button className={styles.primaryButton} onClick={upload}><Upload size={16}/>Unggah</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(240px,1fr))',gap:16,marginTop:18}}>{data.map(x=><article key={x.id} style={{background:'#fff',border:'1px solid #d8e4f2',borderRadius:14,overflow:'hidden'}}><img src={urlFotoTps3r(x.urlFoto)} alt="Penyerahan sampah" style={{width:'100%',height:190,objectFit:'cover'}}/><div style={{padding:12,display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong>{new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(x.tanggal))}</strong><button className={styles.iconButtonDanger} onClick={async()=>{if(confirm('Hapus foto ini?')){await tps3rApi.hapusFoto(x.id);load()}}}><Trash2 size={14}/></button></div></article>)}</div></div>
}
