ALTER TABLE "eprom_vendors"
ADD COLUMN "menu_nonaktif" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TYPE "EpromSafetyMeetingType" ADD VALUE IF NOT EXISTS 'DOKPRO';
ALTER TYPE "EpromSafetyMeetingType" ADD VALUE IF NOT EXISTS 'IZIN_KERJA_KHUSUS';
